
PROGRAM=./Greedy-QAP.py
SOLDIRECTORY=./qapsoln/
DATADIRECTORY=./qapdata/
SHELL=/bin/bash
DATAFILES=`ls -c $(DATADIRECTORY)`
%:
	$(PROGRAM) $@
greedy:
	./script.sh $(DATADIRECTORY) $(PROGRAM) ./solutionGreedy/
